version: "3"

services:
  scylla:
    container_name: scylla
    image: scylladb/scylla:5.2.0
    restart: always
    ports:
      - '9042:9042'
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

#  app:
#    container_name: app
#    image: rinha-backend-2024-q1:latest
#    restart: always
#    ports:
#      - '9091:9091'
#    environment:
#      SCYLLA_HOST: scylla
#      SCYLLA_PORT: 9042
#    depends_on:
#      scylla:
#        condition: service_healthy
