version: "3"

services:
  scylla:
    container_name: scylla
    image: scylladb/scylla:5.2.0
    restart: always
    command: --smp 1 --memory 1G
    ports:
      - '9042:9042'
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5

#  app:
#    container_name: app
#    image: rinha-backend-2024-q1:latest
#    restart: always
#    ports:
#      - '9091:9091'
#    environment:
#      SCYLLA_HOST: scylla
#      SCYLLA_PORT: 9042
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#    depends_on:
#      scylla:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
